/*
   Sample flake to demonstrate how to use pix in a non-deterministic way.
*/

{
  inputs = {
    pix.url = "github:peromage/pix/master";

    ## Override nixpkgs
    #nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";
    #pix.inputs.nixpkgs.follows = "nixpkgs"
  };

  outputs = { self, pix, ... }:
    let
      lib = pix.inputs.nixpkgs.lib;

    in {
      ## Override some attributes in the original configuration
      nixosConfigurations.default = pix.nixosConfigurations.Framework.extend (final: prev: {
        modules = prev.modules ++ [{
          pix.system.hostName = lib.mkForce "Foo";
          pix.system.immutableUsers = true;
          pix.users.fang.password = "mkpassword"; ## The hashed password can be generated by `mkpassword'.
        }];
      });
    };
}
