# -*- yaml-indent-offset: 2; -*-

name: Emacs CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  sanity:
    env:
      PEW_TOPLEVEL: dotfiles/emacs/.emacs.d

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          # - 28.1
          # - 28.2
          # - 29.1
          # - 29.2
          # - 29.3
          - 29.4
          - snapshot

    runs-on: ubuntu-latest
    continue-on-error: true

    ##
    ## This is believed to be an unresolved issue from GitHub workflow where
    ## the pending jobs can be accidentally canceled for an unknown reason
    ## saying
    ##   "Canceling since a higher priority waiting request for
    ##   'CI-refs/heads/master' exists"
    ## Currently a workaround is to disable the concurrency.
    ##
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    #   cancel-in-progress: false

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Test - Fresh startup with package installation
        working-directory: ${{ PEW_TOPLEVEL }}
        run: ./pew/tests/test-init.sh $(pwd)

      - name: Test - Normal startup
        working-directory: ${{ PEW_TOPLEVEL }}
        run: ./pew/tests/test-init.sh $(pwd)

      - name: Test - Mini startup
        working-directory: ${{ PEW_TOPLEVEL }}
        run: ./pew/tests/test-init-mini.sh $(pwd)

      - name: Test - pewcfg unittest
        working-directory: ${{ PEW_TOPLEVEL }}/pew/site-lisp/pewcfg
        run: ./tests/run-tests.sh $(pwd)
